#!/bin/bash

# change to the directory where the script lives, so that the relative paths all work
cd `dirname $0`

# check that the user is root
if [ "$(id -u)" != "0" ]
then
 echo "You must be root to run this script. Uninstall failed."
 exit 9
fi

/etc/init.d/csx stop  >/dev/null 2>&1

if [ -x /usr/lib/lsb/remove_initd ]
  then
    /usr/lib/lsb/remove_initd /etc/init.d/csx 2>/dev/null
    rm -f /etc/init.d/csx
  elif [ -x /sbin/chkconfig ]
  then
    /sbin/chkconfig --del csx 2>/dev/null
    rm -f /etc/init.d/csx
  else
    echo Platform not supported for init.d removal
fi

# clean up after builds
make clean 2>/dev/null

# remove the module
if  uname -r | grep "^2\.4" > /dev/null
then 
  suffix=o
else 
  suffix=ko
fi

rm -f /lib/modules/`uname -r`/kernel/drivers/misc/csx.$suffix 

/sbin/rmmod csx 2>/dev/null
rm -f /dev/csx[0-9]{m,c} /dev/csx[0-9][0-9]{m,c}
/sbin/depmod

# check that we really did remove csx
/sbin/lsmod | grep -e "^csx "  >/dev/null
if [ $? = 0 ]
then 
 echo "Could not remove csx module - it is still in use (are you running a program?).  Operation failed."
 exit 9
fi
